import Head from 'next/head'
import About from '../components/About'
import Blog from '../components/Blog'
import Counter from '../components/Counter'
import Footer from '../components/Footer'
// import Image from 'next/image'
import Header from '../components/Header'
import Hero from '../components/Hero'
import Portfolio from '../components/Portfolio'
import Pricing from '../components/Pricing'
import Services from '../components/Services'
import Testimonials from '../components/Testimonials'
// import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>NextJS Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero />
      <Services />
      <About />
      <Portfolio />
      <Counter />
      <Testimonials />
      <Pricing />
      <Blog />
      <Footer />
    </div>
  )
}
